# ==========================================================
# namespace
# ==========================================================
apiVersion: v1
kind: Namespace
metadata:
    name: citus

---
# ==========================================================
# storageclass
# ==========================================================

---
# ----------------------------------------------------------
# citus-coordinator-x-storage
# ----------------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: citus-coordinator-1-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: citus-coordinator-2-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false

---
# ----------------------------------------------------------
# citus-worker-x-storage
# ----------------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: citus-worker-1-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: citus-worker-2-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false

---
# ----------------------------------------------------------
# pg-locker-storage
# ----------------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: pg-locker-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false


# ==========================================================
# citus-coordinator-1
# ==========================================================

---
# ----------------------------------------------------------
# service
# ----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: citus-coordinator-1
    namespace: citus
spec:
    selector:
        app: citus-coordinator-1
    ports:
        - port: 5432
          targetPort: 5432

---
# ----------------------------------------------------------
# statefulset
# ----------------------------------------------------------
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: citus-coordinator-1
    namespace: citus
spec:
    serviceName: citus-coordinator-1
    replicas: 1
    selector:
        matchLabels:
            app: citus-coordinator-1
    template:
        metadata:
            labels:
                app: citus-coordinator-1
        spec:
            containers:
                - name: citus-coordinator-1
                  image: citusdata/citus:latest
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "111"
                      - name: PGUSER
                        value: "postgres"
                      - name: PGPASSWORD
                        value: "111"
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/postgresql/18/docker
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes:
                  - ReadWriteOnce
              storageClassName: citus-coordinator-1-storage
              resources:
                  requests:
                      storage: 10Gi


# ==========================================================
# citus-coordinator-2
# ==========================================================

---
# ----------------------------------------------------------
# service
# ----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: citus-coordinator-2
    namespace: citus
spec:
    selector:
        app: citus-coordinator-2
    ports:
        - port: 5432
          targetPort: 5432

---
# ----------------------------------------------------------
# statefulset
# ----------------------------------------------------------
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: citus-coordinator-2
    namespace: citus
spec:
    serviceName: citus-coordinator-2
    replicas: 1
    selector:
        matchLabels:
            app: citus-coordinator-2
    template:
        metadata:
            labels:
                app: citus-coordinator-2
        spec:
            containers:
                - name: citus-coordinator-2
                  image: citusdata/citus:latest
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "111"
                      - name: PGUSER
                        value: "postgres"
                      - name: PGPASSWORD
                        value: "111"
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/postgresql/18/docker
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes:
                  - ReadWriteOnce
              storageClassName: citus-coordinator-2-storage
              resources:
                  requests:
                      storage: 10Gi


# ==========================================================
# citus-worker-1
# ==========================================================

---
# ----------------------------------------------------------
# service
# ----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: citus-worker-1-headless
    namespace: citus
spec:
    clusterIP: None
    selector:
        app: citus-worker-1
    ports:
        - port: 5432
          targetPort: 5432

---
# ----------------------------------------------------------
# statefulset
# ----------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: citus-worker-1
    namespace: citus
spec:
    serviceName: citus-worker-1-headless
    replicas: 3
    selector:
        matchLabels:
            app: citus-worker-1
    template:
        metadata:
            labels:
                app: citus-worker-1
        spec:
            containers:
                - name: citus-worker-1
                  image: citusdata/citus:latest
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "111"
                      - name: PGUSER
                        value: "postgres"
                      - name: PGPASSWORD
                        value: "111"
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/postgresql
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes:
                  - ReadWriteOnce
              storageClassName: citus-worker-1-storage
              resources:
                  requests:
                      storage: 10Gi


# ==========================================================
# citus-worker-2
# ==========================================================

---
# ----------------------------------------------------------
# service
# ----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: citus-worker-2-headless
    namespace: citus
spec:
    clusterIP: None
    selector:
        app: citus-worker-2
    ports:
        - port: 5432
          targetPort: 5432

---
# ----------------------------------------------------------
# statefulset
# ----------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: citus-worker-2
    namespace: citus
spec:
    serviceName: citus-worker-2-headless
    replicas: 3
    selector:
        matchLabels:
            app: citus-worker-2
    template:
        metadata:
            labels:
                app: citus-worker-2
        spec:
            containers:
                - name: citus-worker-2
                  image: citusdata/citus:latest
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "111"
                      - name: PGUSER
                        value: "postgres"
                      - name: PGPASSWORD
                        value: "111"
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/postgresql
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes:
                  - ReadWriteOnce
              storageClassName: citus-worker-2-storage
              resources:
                  requests:
                      storage: 10Gi


# ==========================================================
# postgresql-locker
# ==========================================================
---
# ----------------------------------------------------------
# service
# ----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: pg-locker
    namespace: citus
spec:
    selector:
        app: pg-locker
    ports:
        - port: 5432
          targetPort: 5432


# ----------------------------------------------------------
# statefulset
# ----------------------------------------------------------
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: pg-locker
    namespace: citus
spec:
    serviceName: pg-locker
    replicas: 1
    selector:
        matchLabels:
            app: pg-locker
    template:
        metadata:
            labels:
                app: pg-locker
        spec:
            containers:
                - name: postgres
                  image: postgres:latest
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        value: "postgres"
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "111"
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/postgresql
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes:
                  - ReadWriteOnce
              storageClassName: pg-locker-storage
              resources:
                  requests:
                      storage: 5Gi
