apiVersion: v1
kind: Namespace
metadata:
    name: citus


# ==========================================================
# citus-coordinator
# ==========================================================
---
apiVersion: v1
kind: Service
metadata:
    name: citus-coordinator
    namespace: citus
spec:
    selector:
        app: citus-coordinator
    ports:
        - port: 5432
          targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: citus-coordinator
    namespace: citus
spec:
    serviceName: citus-coordinator
    replicas: 1
    selector:
        matchLabels:
            app: citus-coordinator
    template:
        metadata:
            labels:
                app: citus-coordinator
        spec:
            containers:
                - name: citus-coordinator
                  image: citusdata/citus:13.0.3
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "111"
                      - name: PGUSER
                        value: "postgres"
                      - name: PGPASSWORD
                        value: "111"
                      - name: POSTGRES_HOST_AUTH_METHOD
                        value: "trust"


# ==========================================================
# citus-worker
# ==========================================================
---
apiVersion: v1
kind: Service
metadata:
    name: citus-worker-headless
    namespace: citus
spec:
    clusterIP: None
    selector:
        app: citus-worker
    ports:
        - port: 5432
          targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: citus-worker
    namespace: citus
spec:
    serviceName: citus-worker-headless
    replicas: 5
    selector:
        matchLabels:
            app: citus-worker
    template:
        metadata:
            labels:
                app: citus-worker
        spec:
            containers:
                - name: citus-worker
                  image: citusdata/citus:13.0.3
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "111"
                      - name: PGUSER
                        value: "postgres"
                      - name: PGPASSWORD
                        value: "111"
                      - name: POSTGRES_HOST_AUTH_METHOD
                        value: "trust"
