-- DROP TABLE IF EXISTS REJECTED_ORDER;
-- DROP TABLE IF EXISTS ORDER_ITEM;
-- DROP TABLE IF EXISTS APP_ORDER;
-- DROP TABLE IF EXISTS CAR_IMAGE;
-- DROP TABLE IF EXISTS CAR_SERVICE_HISTORY;
-- DROP TABLE IF EXISTS CAR_PASSPORT;
-- DROP TABLE IF EXISTS CAR;
-- DROP TABLE IF EXISTS PROFILE_FILTER_CAPACITY;
-- DROP TABLE IF EXISTS PROFILE_FILTER_USAGE_TYPE;
-- DROP TABLE IF EXISTS PROFILE_FILTER_TRANSMISSION_TYPE;
-- DROP TABLE IF EXISTS PROFILE_FILTER_DRIVE_TYPE;
-- DROP TABLE IF EXISTS PROFILE_FILTER_BRAND;
-- DROP TABLE IF EXISTS CAPACITY;
-- DROP TABLE IF EXISTS CAPACITY_TYPE;
-- DROP TABLE IF EXISTS USAGE_TYPE;
-- DROP TABLE IF EXISTS TRANSMISSION_TYPE;
-- DROP TABLE IF EXISTS DRIVE_TYPE;
-- DROP TABLE IF EXISTS BRAND;
-- DROP TABLE IF EXISTS APP_USER;
-- DROP TABLE IF EXISTS APP_USER_PROFILE;
-- DROP TABLE IF EXISTS APP_ROLE;
CREATE TABLE
    APP_ROLE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        NAME VARCHAR(100) NOT NULL
    );

CREATE TABLE
    APP_USER_PROFILE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        NAME VARCHAR(100) NOT NULL,
        APP_ROLE_ID UUID REFERENCES APP_ROLE (ID),
        IS_DELETED BOOLEAN DEFAULT FALSE
    );

CREATE TABLE
    APP_USER (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        EMAIL VARCHAR(250) UNIQUE NOT NULL,
        PASSWORD VARCHAR(128) NOT NULL,
        APP_USER_PROFILE_ID UUID REFERENCES APP_USER_PROFILE (ID)
    );

CREATE TABLE
    BRAND (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        NAME VARCHAR(100) NOT NULL
    );

CREATE TABLE
    DRIVE_TYPE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        NAME VARCHAR(100) NOT NULL
    );

CREATE TABLE
    TRANSMISSION_TYPE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        NAME VARCHAR(100) NOT NULL
    );

CREATE TABLE
    USAGE_TYPE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        NAME VARCHAR(100) NOT NULL
    );

CREATE TABLE
    CAPACITY_TYPE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        NAME VARCHAR(100) NOT NULL
    );

CREATE TABLE
    CAPACITY (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        VALUE INT NOT NULL CHECK (VALUE > 0),
        CAPACITY_TYPE_ID UUID REFERENCES CAPACITY_TYPE (ID)
    );

CREATE TABLE
    PROFILE_FILTER_BRAND (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        APP_USER_PROFILE_ID UUID REFERENCES APP_USER_PROFILE (ID),
        BRAND_ID UUID REFERENCES BRAND (ID)
    );

CREATE TABLE
    PROFILE_FILTER_DRIVE_TYPE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        APP_USER_PROFILE_ID UUID REFERENCES APP_USER_PROFILE (ID),
        DRIVE_TYPE_ID UUID REFERENCES DRIVE_TYPE (ID)
    );

CREATE TABLE
    PROFILE_FILTER_TRANSMISSION_TYPE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        APP_USER_PROFILE_ID UUID REFERENCES APP_USER_PROFILE (ID),
        TRANSMISSION_TYPE_ID UUID REFERENCES TRANSMISSION_TYPE (ID)
    );

CREATE TABLE
    PROFILE_FILTER_USAGE_TYPE (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        APP_USER_PROFILE_ID UUID REFERENCES APP_USER_PROFILE (ID),
        USAGE_TYPE_ID UUID REFERENCES USAGE_TYPE (ID)
    );

CREATE TABLE
    PROFILE_FILTER_CAPACITY (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        APP_USER_PROFILE_ID UUID REFERENCES APP_USER_PROFILE (ID),
        CAPACITY_ID UUID REFERENCES CAPACITY (ID)
    );

CREATE TABLE
    CAR (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        BRAND_ID UUID REFERENCES BRAND (ID),
        DRIVE_TYPE_ID UUID REFERENCES DRIVE_TYPE (ID),
        TRANSMISSION_TYPE_ID UUID REFERENCES TRANSMISSION_TYPE (ID),
        USAGE_TYPE_ID UUID REFERENCES USAGE_TYPE (ID),
        CAPACITY_ID UUID REFERENCES CAPACITY (ID)
    );

CREATE TABLE
    CAR_PASSPORT (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        NAME VARCHAR(100) NOT NULL,
        DESCRIPTION TEXT NOT NULL,
        PRICE_OF_ORIGIN DECIMAL(12, 2) NOT NULL CHECK (PRICE_OF_ORIGIN > 0),
        MANUFACTURE_DATE DATE NOT NULL,
        COUNTRY_OF_ORIGIN VARCHAR(100) NOT NULL,
        VIN VARCHAR(17) UNIQUE NOT NULL,
        ACCIDENT_COUNT INT DEFAULT 0 CHECK (ACCIDENT_COUNT >= 0),
        CAR_ID UUID REFERENCES CAR (ID),
        IS_DELETED BOOLEAN DEFAULT FALSE
    );

CREATE TABLE
    APP_ORDER (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        ORDER_DATE DATE NOT NULL,
        COMMENT TEXT,
        STATUS VARCHAR(50) DEFAULT 'PENDING',
        PERIOD_MONTHS INT NOT NULL CHECK (PERIOD_MONTHS > 0),
        DOWN_PAYMENT DECIMAL(12, 2) NOT NULL CHECK (DOWN_PAYMENT > 0),
        MONTHLY_PAYMENT DECIMAL(12, 2) NOT NULL CHECK (MONTHLY_PAYMENT > 0),
        APP_USER_ID UUID REFERENCES APP_USER (ID),
        MANAGER_ID UUID REFERENCES APP_USER (ID),
        IS_DELETED BOOLEAN DEFAULT FALSE
    );

CREATE TABLE
    ORDER_ITEM (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        CAR_ID UUID REFERENCES CAR (ID),
        APP_ORDER_ID UUID REFERENCES APP_ORDER (ID)
    );

CREATE TABLE
    REJECTED_ORDER (
        ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
        REASON TEXT,
        CREATED_AT TIMESTAMP DEFAULT NOW (),
        APP_ORDER_ID UUID REFERENCES APP_ORDER (ID),
        APP_MANAGER_ID UUID REFERENCES APP_USER (ID)
    );